# Generated by Django 4.2.4 on 2023-08-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appuser_slug_userprofile_age_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
