# Generated by Django 4.2.4 on 2023-08-12 10:26

import XroutS.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_appuser_slug_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='user_picture/', validators=[XroutS.core.validators.validate_file_size]),
        ),
    ]
