# Generated by Django 4.2.4 on 2023-08-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_gpsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyclingactivity',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='runningactivity',
            name='route',
        ),
        migrations.RemoveField(
            model_name='swimmingactivity',
            name='elevation',
        ),
    ]
