# Generated by Django 4.2.4 on 2023-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_cyclingactivity_picture_runningactivity_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclingactivity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='runningactivity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='swimmingactivity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
