# Generated by Django 4.2.4 on 2023-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0001_initial'),
        ('activities', '0005_alter_cyclingactivity_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclingactivity',
            name='likes',
            field=models.ManyToManyField(blank=True, to='functionalities.like'),
        ),
        migrations.AddField(
            model_name='runningactivity',
            name='likes',
            field=models.ManyToManyField(blank=True, to='functionalities.like'),
        ),
        migrations.AddField(
            model_name='swimmingactivity',
            name='likes',
            field=models.ManyToManyField(blank=True, to='functionalities.like'),
        ),
    ]
