# Generated by Django 4.2.4 on 2023-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_cyclingactivity_likes_runningactivity_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdata',
            name='cadance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='hr',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
