# Generated by Django 4.2.4 on 2023-08-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_gpsdata_cadance_gpsdata_distance_gpsdata_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='cadance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='hr',
            field=models.FloatField(null=True),
        ),
    ]
