# Generated by Django 4.2.4 on 2023-08-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_gpsdata_cadance_alter_gpsdata_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField()),
                ('duration', models.CharField()),
                ('pace', models.CharField()),
            ],
        ),
    ]
