# Generated by Django 4.2.4 on 2023-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_alter_gpsdata_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclingactivity',
            name='date_of_activity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cyclingactivity',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='runningactivity',
            name='date_of_activity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runningactivity',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='swimmingactivity',
            name='date_of_activity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swimmingactivity',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
